version: '3'          

services: 

    jenkins:
        image: jenkins/jenkins:jdk11
        container_name: jenkins-compose
        ports:
            - "50000:50000"
            - "8880:8080"
        volumes:
            - ../volumes/jenkins:/var/jenkins_home
        networks:
            - docker_network

    ubuntu_slave:
        depends_on: 
            - jenkins
        container_name: ubuntu-compose
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        build: 
            context: ../dockerfiles/slave
        command: java -jar agent.jar -jnlpUrl http://192.168.44.44:8880/computer/Slave/jenkins-agent.jnlp -secret fda12d51237c01d58eba8f59bbcf591c31844016c38e8b8a70573508a74a527f -workDir "/home/"
        networks: 
            - docker_network

    selenium_hub:
        image: selenium/hub
        container_name: seleniumhub-compose
        ports: 
            - "4444:4444"
        networks: 
            - docker_network

    selenium_node:
        image: selenium/node-firefox
        container_name: firefox-compose
        depends_on: 
            - selenium_hub
        environment: 
            - HUB_HOST=seleniumhub-compose
            - HUB_PORT=4444
        networks: 
            - docker_network

    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:latest
        container_name: artifactory-compose
        volumes: 
            - ../volumes/artifactory:/var/jfrog/artifactory
        ports: 
            - "8081:8082"
            - "8082:8082"
        networks: 
            - docker_network

networks: 
    docker_network:
        driver: bridge
